// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPhies_FHIR_Integration.Infrastructure.Data;

#nullable disable

namespace NPhies_FHIR_Integration.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624120000_AddMasterDataTables")]
    partial class AddMasterDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
   {
#pragma warning disable 612, 618
            modelBuilder
         .HasAnnotation("ProductVersion", "9.0.0")
       .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

     // Master table configurations would go here
#pragma warning restore 612, 618
        }
    }
}
