using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore;
using Nphies.Core.Data.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Threading;
using Nphies.Core.Data.Common;
using System.Linq;
using Nphies.Core.Models;

namespace Nphies.Core.Data.Entities
{
    public partial class ZyklusCoreContext
    {
        public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            var auditEntries = OnBeforeSaveChanges();
            var result = await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
            await OnAfterSaveChanges(auditEntries);
            return result;
        }

        private List<AuditEntry> OnBeforeSaveChanges()
        {
            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is RcmClaimServicesDetail || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                {
                  var rcmClaimServicesDetail = entry.Entity as RcmClaimServicesDetail;
                    
                    if (rcmClaimServicesDetail != null 
                        && rcmClaimServicesDetail.Status == (byte)ClaimStatus.Nphies_Rejected)
                    {
                        var auditEntry = new AuditEntry(entry);
                        auditEntry.TableName = entry.Metadata.GetTableName();
                        auditEntry.ClaimId = rcmClaimServicesDetail.ClaimId;
                        auditEntry.ServiceId=   rcmClaimServicesDetail.ServiceId;
                        auditEntry.OrganizationId = rcmClaimServicesDetail.OrganizationId;
                        auditEntry.RowId = rcmClaimServicesDetail.RowId;
                        auditEntry.NphiesSeqNo = rcmClaimServicesDetail.NphiesSeqNo.HasValue ? rcmClaimServicesDetail.NphiesSeqNo.Value : 0;
                        auditEntry.ReasonCode = rcmClaimServicesDetail.ReasonCode;
                        auditEntry.ItemReason = rcmClaimServicesDetail.ItemReason;
                        auditEntries.Add(auditEntry);

                        foreach (var property in entry.Properties)
                        {
                            if (property.IsTemporary)
                            {
                                // value will be generated by the database, get the value after saving
                                auditEntry.TemporaryProperties.Add(property);
                                continue;
                            }

                            string propertyName = property.Metadata.Name;
                            if (property.Metadata.IsPrimaryKey())
                            {
                                auditEntry.KeyValues[propertyName] = property.CurrentValue;
                                continue;
                            }
                            if (property.Metadata.Name.ToLower().Equals("createdby"))
                                auditEntry.CreatedBy = (int)property.CurrentValue;

                            switch (entry.State)
                            {
                                case EntityState.Modified:
                                    if (property.IsModified)
                                    {
                                        auditEntry.OldValues[propertyName] = property.OriginalValue;
                                        auditEntry.NewValues[propertyName] = property.CurrentValue;
                                    }
                                    break;
                            }
                        }
                    }
                   
                }
                

               
            }

            // Save audit entities that have all the modifications
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                AuditLogs.Add(auditEntry.ToAudit());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }

        private Task OnAfterSaveChanges(List<AuditEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
                return Task.CompletedTask;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                AuditLogs.Add(auditEntry.ToAudit());
            }

            return SaveChangesAsync();
        }
    }
}
